name: Vitest tests
on:
  push:
    branches: ["main"]
    
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: Install dependancies
        run: npm ci
      - name: Run Tests
        run: npm run test:unit


